### ISSUE TITLE
git commit hook bug: blocked by call to non-existent vendor/depot_tools/cpplint.py

### ISSUE THREAD

**Issue by garvankeeley** [brave/ad-block#12]
Output of a commit for me looks like
$git commit 
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/gkeeley/brave/abp-filter-parser-cpp/vendor/depot_tools/cpplint.py'

**Comment by bbondy** [comment]
You need to install the submodules, `git clone --recursive repourl`, or else you can just git submodule update --init
