### ISSUE TITLE
Google 2FA is broken

### ISSUE THREAD

**Issue by Rutrus** [brave/ad-block#131]
I use "native" 2FA for my Google Account, which is integrated in Android. My device receives a push notification correctly, but the browser instantly shows me "time is expired" asking to try again.

**Comment by bsclifton** [comment]
@Rutrus are you using the Desktop Brave browser? Or the Android version?

**Comment by Rutrus** [comment]
Oh ok, thank you. It was in desktop version. The thread can be closed.
