### ISSUE TITLE
How to use this inside Chromium?

### ISSUE THREAD

**Issue by shadowysean** [brave/ad-block#132]
Wonder if it's possible to back-port this cool lib to Chromium? I'm rather new to Node so not sure if I can integrate this directly by simply changing some lines of build conf files. If so, and say I want to use it in third_party/blink, how should I proceed to embed its dependencies (all native Node modules as I see?)?

Thanks a lot!

**Comment by bbondy** [comment]
https://github.com/brave/brave-core uses it in chromium
