### ISSUE TITLE
New York Times videos are not playing with ad block turned on

### ISSUE THREAD

**Issue by erchaves** [brave/ad-block#179]
Steps to reproduce: 
- In brave desktop: whatsmybrowser.org/b/SPUXK54
- View a New York Times video page (e.g. https://www.nytimes.com/2019/02/19/science/spittlebugs-bubble-home.html)
- try to play video
- The video just turns black and nothing happens. 

I'm not sure if github issues are the proper place to report this, but I hope we can gradually fix these edge cases. Because I want to tell everyone to switch to Brave. But it's hard to tell my friends to switch when they tell me their everyday sites are "broken" in brave just because of tiny edge cases like this one. I do see that other issues were reported for certain videos being blocked and they were addressed, so I'm hoping that it's helpful to report this other specific case. https://github.com/brave/ad-block/issues/119

Thanks!

**Comment by erchaves** [comment]
P.S. @NYTimes, I've been sending you BAT tips that are waiting for you if you claim your BAT account. Please support BAT and take my monies! Thanks for your continued important work.

**Comment by bbondy** [comment]
This is fixed as of Brave 0.63.x currently on Beta channel. It will hit release channel around April 23.

**Comment by erchaves** [comment]
Amazing, thanks so much for your efforts!
