### ISSUE TITLE
Disconnect list is redundant if Google Safe Browsing is enabled

### ISSUE THREAD

**Issue by fmarier** [brave/ad-block#186]
I looked at the Disconnect [simple malware list](https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt) which we [include as part of `SafeBrowsingData.dat`](https://github.com/brave/ad-block/blob/c02a65217e5e989294fef06ce4a2e099c9c10c4b/lists/malware.h#L22-L30). It consists of only 53 entries. I tested it manually:

    wget https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt
    for u in `tail -n +5 simple_malware.txt` ; do google-chrome --incognito $u ; done

and found that Google Safe Browsing blocked all of the entries except for:

- `http://191gm.com/` (dead)
- `http://malware-check.disconnect.me/` (presumably their test host)

I think we can safely remove it on platforms that have Google Safe Browsing enabled.

**Comment by bbondy** [comment]
@SergeyZhukovsky are you guys using it?

**Comment by bbondy** [comment]
Brave-Core doesn't use it
Muon used it but is deprecated
iOS doesn't have Google Safe Browsing, @jhreis does the new browser use it?

**Comment by SergeyZhukovsky** [comment]
Android doesn't have Safe Browsing.

**Comment by bbondy** [comment]
Google Safe Browsing or brave/ad-block Safe Browsing?

**Comment by SergeyZhukovsky** [comment]
SafeBrowsingData.dat for sure isn't used in Android. I'm not sure how to check about Google's one. We have never made any work related to that. @fmarier could you please check it?

**Comment by fmarier** [comment]
Here's the current state of Safe Browsing across our supported browsers:

browser | Google Safe Browsing | `SafeBrowsingData.dat`
------------------------------- | ---------------- | --------------
brave-core | yes | no
browser-android-tabs | [no](https://github.com/brave/browser-android-tabs/issues/454) | [no](https://github.com/brave/browser-android-tabs/issues/1212)
brave-ios | [no](https://github.com/brave/brave-ios/issues/483) | yes

Test pages for each:
- Google Safe Browsing: <https://testsafebrowsing.appspot.com>
- `SafeBrowsingData.dat`: <http://excellentmovies.net>

**Comment by bbondy** [comment]
Thanks @fmarier !
I think @jumde  could get Google Safe Browsing working in Android pretty easily using code he did in Brave-core.

**Comment by jumde** [comment]
There are issues opened in `brave-ios` and `android`, assigned the issue to myself: 
- https://github.com/brave/brave-ios/issues/483
- https://github.com/brave/browser-android-tabs/issues/454

**Comment by bbondy** [comment]
Closing this since we emptied the safe browsing lists.
