### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by 736980900** [brave/ad-block#202]
I use the latest code on android,but he always crash.There three kinds of crash stack as follow.help me please~ Thank you very very much!

SIGSEGV(SEGV_MAPERR):
#00 pc 00a79c8c libwebview.so HashSetForAds<FilterForAds>::Find(FilterForAds const&)(../../adblock/hash_set.h:145) + 0x0
#01 pc 00a79d49 libwebview.so isHostAnchoredHashSetMiss(char const*, int, HashSetForAds<FilterForAds>*, char const*, int, FilterOption, char const*, FilterForAds**)(../../adblock/hash_set.h:754) + 0x5
#02 pc 00a7c003 libwebview.so AdBlockClient::matches(char const*, FilterOption, char const*, FilterForAds**, FilterForAds**)(../../adblock/ad_block_client.cc:845) + 0x17

SIGFPE:
#00 pc 0004a630 /vendor/lib/libpq_prot.so (tgkill+12) [armeabi-v8::55b233330ae519e1ab1abdd92db862a4]
#01 pc 00085584 /data/app/com.mtt.mtt--5cdFagKMK3lyHLYTiiV9Q==/lib/arm/libmtt_shared.so (__aeabi_idiv0+8) [armeabi-v7a::9a8967945cb02d5f315fcad64a7bdb4a]
#02 pc 00a79bcf libwebview.so HashSetForAds<NoFingerprintDomain>::Find(NoFingerprintDomain const&)(../../adblock/hash_set.h:139) + 0x7
#03 pc 00a79c35 libwebview.so isNoFingerprintDomainHashSetMiss(HashSetForAds<NoFingerprintDomain>*, char const*, int)(../../adblock/hash_set.h:706) + 0x5
#04 pc 00a7bf3b libwebview.so AdBlockClient::matches(char const*, FilterOption, char const*, FilterForAds**, FilterForAds**)(../../adblock/ad_block_client.cc:814) + 0x7

SIGSEGV(SEGV_MAPERR):
#00 pc 00a7c6f6 libwebview.so FilterForAds::getDomainCount(bool)(../../adblock/filter.cc:210) + 0x4
#01 pc 00a7c70f libwebview.so FilterForAds::contextDomainMatchesFilter(char const*)(../../adblock/filter.cc:365) + 0x5
#02 pc 00a7c7e5 libwebview.so FilterForAds::matchesOptions(char const*, FilterOption, char const*)(../../adblock/filter.cc:444) + 0x5
#03 pc 00a7c823 libwebview.so FilterForAds::matches(char const*, int, FilterOption, char const*, BloomFilter*, char const*, int)(../../adblock/filter.cc:523) + 0x1
#04 pc 00a7966b libwebview.so AdBlockClient::hasMatchingFilters(FilterForAds*, int, char const*, int, FilterOption, char const*, BloomFilter*, char const*, int, FilterForAds**)(../../adblock/hashFn.h:649) + 0x15
#05 pc 00a7bf9f libwebview.so AdBlockClient::matches(char const*, FilterOption, char const*, FilterForAds**, FilterForAds**)(../../adblock/ad_block_client.cc:826) + 0x21

**Comment by bbondy** [comment]
Could you please attach any source code used for the crash? thanks.

**Comment by bbondy** [comment]
If you use 4.1.4 you should be ok. It was probably that you were using an old version and it pointed to an adblock list which no longer exists.

**Comment by ymh8416** [comment]
> I use the latest code on android,but he always crash.There three kinds of crash stack as follow.help me please~ Thank you very very much!
> 
> SIGSEGV(SEGV_MAPERR):
> #00 pc 00a79c8c libwebview.so HashSetForAds::Find(FilterForAds const&)(../../adblock/hash_set.h:145) + 0x0
> #1 pc 00a79d49 libwebview.so isHostAnchoredHashSetMiss(char const*, int, HashSetForAds_, char const_, int, FilterOption, char const*, FilterForAds**)(../../adblock/hash_set.h:754) + 0x5
> #2 pc 00a7c003 libwebview.so AdBlockClient::matches(char const*, FilterOption, char const*, FilterForAds**, FilterForAds**)(../../adblock/ad_block_client.cc:845) + 0x17
> 
> SIGFPE:
> #00 pc 0004a630 /vendor/lib/libpq_prot.so (tgkill+12) [armeabi-v8::55b233330ae519e1ab1abdd92db862a4]
> #1 pc 00085584 /data/app/com.mtt.mtt--5cdFagKMK3lyHLYTiiV9Q==/lib/arm/libmtt_shared.so (__aeabi_idiv0+8) [armeabi-v7a::9a8967945cb02d5f315fcad64a7bdb4a]
> #2 pc 00a79bcf libwebview.so HashSetForAds::Find(NoFingerprintDomain const&)(../../adblock/hash_set.h:139) + 0x7
> #3 pc 00a79c35 libwebview.so isNoFingerprintDomainHashSetMiss(HashSetForAds_, char const_, int)(../../adblock/hash_set.h:706) + 0x5
> #4 pc 00a7bf3b libwebview.so AdBlockClient::matches(char const*, FilterOption, char const*, FilterForAds**, FilterForAds**)(../../adblock/ad_block_client.cc:814) + 0x7
> 
> SIGSEGV(SEGV_MAPERR):
> #00 pc 00a7c6f6 libwebview.so FilterForAds::getDomainCount(bool)(../../adblock/filter.cc:210) + 0x4
> #1 pc 00a7c70f libwebview.so FilterForAds::contextDomainMatchesFilter(char const*)(../../adblock/filter.cc:365) + 0x5
> #2 pc 00a7c7e5 libwebview.so FilterForAds::matchesOptions(char const*, FilterOption, char const*)(../../adblock/filter.cc:444) + 0x5
> #3 pc 00a7c823 libwebview.so FilterForAds::matches(char const*, int, FilterOption, char const*, BloomFilter*, char const*, int)(../../adblock/filter.cc:523) + 0x1
> #4 pc 00a7966b libwebview.so AdBlockClient::hasMatchingFilters(FilterForAds*, int, char const*, int, FilterOption, char const*, BloomFilter*, char const*, int, FilterForAds**)(../../adblock/hashFn.h:649) + 0x15
> #5 pc 00a7bf9f libwebview.so AdBlockClient::matches(char const*, FilterOption, char const*, FilterForAds**, FilterForAds**)(../../adblock/ad_block_client.cc:826) + 0x21

I also encountered the same problem. Do you have a solution?
