### ISSUE TITLE
Reek - Anti-AdBlock blocklist testing

### ISSUE THREAD

**Issue by lukemulks** [brave/ad-block#50]
Need to test the Reek anti-ad-blocking blocklist out in Brave. May help ease cat and mouse pains. 

Repo:
https://github.com/reek/anti-adblock-killer#anti-adblock-killer--reek

**Comment by bbondy** [comment]
would you just like this available as a switch alongsite the regional ones inside about:adblock?

**Comment by lukemulks** [comment]
@bbondy apologies for not closing this sooner, we can disregard. The repo in question is no longer maintained, and the 1p exceptions that you put in place for us to use can work instead of this for these cases.
