### ISSUE TITLE
cleaner example or documentation

### ISSUE THREAD

**Issue by myfrndjk** [brave/ad-block#53]
Hi,

I thought of using this package in my project unfortunately I cant understand the JS sample.

URL I want to check if it is ad/tracker  : https://www.google.ie/gen_204?atyp=i&ct=slh&cad=&ei=OdWtWLPnI4mmsgHd4ILgBQ&s=2&v=2&pv=0.6461194853086566&me=10:

domain I loaded/current domain in url bar : www.google.com

Can some one help me to achieve this using brave/ad-block

Thanks

**Comment by bbondy** [comment]
Please see this file which builds a very small utility for checking URLs in different ways. 
https://github.com/brave/ad-block/blob/master/scripts/check.js
