### ISSUE TITLE
Iranian Adblock filter not showing in settings

### ISSUE THREAD

**Issue by Jacalz** [brave/ad-block#55]
In regions.js there is a Iranian filter that doesn't show up in settings 🤐
I found it when I to put the filters in alphabetical order 👍
uuid: 'C3C2F394-D7BB-4BC2-9793-E0F13B2B5971',
 -    listURL: 'https://raw.githubusercontent.com/farrokhi/adblock-iran/master/filter.txt',
 -    title: 'IRN: AdBlock Iran Filter',
 -    lang: 'fa',
 -    supportURL: 'https://github.com/farrokhi/adblock-iran'

**Comment by bbondy** [comment]
Sorry for the delay on this, it'll appear in the next version of Brave 0.14.0. It just needed an npm version bump.
