### ISSUE TITLE
Not works with current nodejs version

### ISSUE THREAD

**Issue by aight8** [brave/ad-block#58]
```
Uncaught Exception:
Error: The module '/.../ad-block/build/Release/ad-block.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
```

**Comment by quanglam2807** [comment]
@aight8 Check: https://stackoverflow.com/questions/42616008/node-module-version-conflict-when-installing-modules-for-electron. You can also use `install-app-deps` command from `electron-builder` to make your life easy.

**Comment by willy-b** [comment]
I had this issue too and `npm install --build-from-source` (after clearing `node_modules`) did the trick for me, though it took a while.

**Comment by bbondy** [comment]
Seems like this has a workaround so closing.  Feel free to open a new issue if there is a specific recommendation.
