### ISSUE TITLE
Add EasyPrivacy list

### ISSUE THREAD

**Issue by lukemulks** [brave/ad-block#68]
EasyPrivacy has been observed catching several domains in addition to those that we filter with disconnect.me TP. Third parties, including FB and others are filtered in uBO with EasyPrivacy. Adding EasyPrivacy will help enhance our TP.

Contents of the EasyPrivacy filter list are fetched from the EasyPrivacy repository:
https://github.com/easylist/easylist/tree/master/easyprivacy

**Comment by rht** [comment]
Had been added since https://github.com/brave/ad-block/commit/0ebbade0045e5c6b67cf3a0fad2b71e90dc5099c#diff-1bf9b629e2a8d17a925c5ac25a89115b.

**Comment by bbondy** [comment]
yep, thx.
