### ISSUE TITLE
Add filter list to prevent browser-based crypto mining

### ISSUE THREAD

**Issue by bernd289** [brave/ad-block#77]
Please add this list to prevent browser-based crypto mining:
https://github.com/hoshsadiq/adblock-nocoin-list

And maybe also ublock Origins Resource Abuse List
https://github.com/uBlockOrigin/uAssets/blob/master/filters/resource-abuse.txt

**Comment by luixxiul** [comment]
+1 from https://github.com/brave/browser-laptop/issues/11832 (coinhive)

**Comment by bernd289** [comment]
https://github.com/brave/ad-block/commit/257e2af197077dbc56a61f59cf4c73ba3d15d2e6
