### ISSUE TITLE
Blob url is blocked, when we probably shouldn't do it

### ISSUE THREAD

**Issue by samartnik** [brave/ad-block#93]
On Android, when we load this page https://jsfiddle.net/7ke9r14a/7/ we block blob url 
blob:https://fiddle.jshell.net/6de81b29-57b1-426d-b8ed-105d7877ffb0 (GUID is autogenerated and always different) with host http://clients1.google.com/ and resource type 1. It causes this issue https://github.com/brave/browser-android-tabs/issues/554
On laptop we don't receive any blob url and therefore don't have such problem.

**Comment by bbondy** [comment]
Fixed in brave/ad-block@4.1.1
